export const GET__REFERRAL__CODE = "GET__REFERRAL__CODE";
export const GET__REFERRAL__CODE__SUCCESS = "GET__REFERRAL__CODE__SUCCESS";
export const GET__REFERRAL__CODE__FAILED = "GET__REFERRAL__CODE__FAILED";
export const GET__REFERRAL__RECORD = "GET__REFERRAL__RECORD";
export const GET__REFERRAL__RECORD__SUCCESS = "GET__REFERRAL__RECORD__SUCCESS";
export const GET__REFERRAL__RECORD__FAILED = "GET__REFERRAL__RECORD__FAILED";
export const GENERATING__REFERRAL__LINK = "GENERATING__REFERRAL__LINK";
export const GENERATE__REFERRAL__LINK__SUCCESS =
    "GENERATE__REFERRAL__LINK__SUCCESS";
export const GENERATE__REFERRAL__LINK__FAILED =
    "GENERATE__REFERRAL__LINK__FAILED";
