/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Erc20 } from "./Erc20";
export type { MMFRouter } from "./MMFRouter";
export type { PolygonmmRouter } from "./PolygonmmRouter";
export type { RanceProtocol } from "./RanceProtocol";
export type { Staking1 } from "./Staking1";
export type { Staking2 } from "./Staking2";
export type { Multicall2 } from "./Multicall2";
export * as factories from "./factories";
export { Erc20__factory } from "./factories/Erc20__factory";
export { MMFRouter__factory } from "./factories/MMFRouter__factory";
export { PolygonmmRouter__factory } from "./factories/PolygonmmRouter__factory";
export { RanceProtocol__factory } from "./factories/RanceProtocol__factory";
export { Staking1__factory } from "./factories/Staking1__factory";
export { Staking2__factory } from "./factories/Staking2__factory";
export { Multicall2__factory } from "./factories/Multicall2__factory";
