export const GET__REFERRAL__CODE = "GET__REFERRAL__CODE";
export const GET__REFERRAL__CODE__SUCCESS = "GET__REFERRAL__CODE__SUCCESS";
export const GET__REFERRAL__CODE__FAILED = "GET__REFERRAL__CODE__FAILED";
export const GET__REFERRAL__RECORD = "GET__REFERRAL__RECORD";
export const GET__REFERRAL__RECORD__SUCCESS = "GET__REFERRAL__RECORD__SUCCESS";
export const GET__REFERRAL__RECORD__FAILED = "GET__REFERRAL__RECORD__FAILED";
