export const GET__PACKAGE__PLANS = "GET__PACKAGE__PLANS";
export const GET__PACKAGE__PLANS__SUCCESS = "GET__PACKAGE__PLANS__SUCCESS";
export const GET__PACKAGE__PLANS__FAILED = "GET__PACKAGE__PLANS__FAILED";
export const GET__USER__PACKAGES = "GET__USER__PACKAGES";
export const GET__USER__PACKAGES__SUCCESS = "GET__USER__PACKAGES__SUCCESS";
export const GET__USER__PACKAGES__FAILED = "GET__USER__PACKAGES__FAILED";
export const REMOVE__USER__PACKAGE = "REMOVE__USER__PACKAGE";